### ISSUE TITLE
Loss only decrease from 2.2 to 1.8

### ISSUE THREAD

**Issue by yqNLP** [snowkylin/line#14]
I use the default setting and your dataset, running 2w batches. It seems the loss wouldn't decease too much, only from 2.2 to 1.8. I wonder if there is something wrong with my experiments?

**Comment by yqNLP** [comment]
the above problem is occurred in first-order, second-order wouldn't have that problem.

**Comment by phucdoitoan** [comment]
Hi, I'm facing the same problems with first-order loss, it only reduces from 1.0 to 0.6-0.7 (which is not much). I wonder if the first-order embedding performs well or not? Anyone gets any idea?

**Comment by phucdoitoan** [comment]
Update: I tried the code with facebook dataset (mentioned in node2vec paper), the 2nd order loss -> 0, the 1st order -> around 0.6-0.7 (didnt go to 0 though). Both embeddings were feasible (test with link prediction task): AUC of 1st and 2nd order is around 0.77 and 0.87

**Comment by Irenehere** [comment]
I have the same problem. The loss is not decreasing.
