### ISSUE TITLE
Question about negative sampling in utils.py

### ISSUE THREAD

**Issue by zhanxiuxiu** [snowkylin/line#4]
Hi,

I read your algorithm and found one part I cannot understand. In the function of fetch_batch, you have the negative sampling for the center node edge[0], but in line 54, you check whether there is an edge between the negative node and edge[1], the line is
`if not self.g.has_edge(self.node_index_reversed[edge[0]], self.node_index_reversed[negative_node])`
If I understand negative sampling correctly,  we need to check whether there is an edge between center node edge[0] and negative node.  If there is no link between them, we can add the negative node as a negative sample for edge[0].

Am I right ? Or I missed something.

Looking forward.

**Comment by snowkylin** [comment]
OMG, it seems like a typo. I have fixed it, thank you for your issue!

**Comment by zhanxiuxiu** [comment]
I think the 'break' used here is also a problem. Do you mean if the negative node is not the neighbor of edge[0], we need to add the negative node as an negative sample ? If I am right, I think this part should be:
if not self.g.has_edge(self.node_index_reversed[negative_node], self.node_index_reversed[edge[0]]):
        u_i.append(edge[0])
        u_j.append(negative_node)
        label.append(-1)

**Comment by zhanxiuxiu** [comment]
The append part should be inside the if loop.

**Comment by snowkylin** [comment]
The 'while-break' structure means that the loop will always continue until an appropriate negative sample is generated through the loop, then we jump out of the loop and add the sample to the batch.

**Comment by zhanxiuxiu** [comment]
Ok, I undertand, thanks.
