### ISSUE TITLE
About the embeddings of second-order similarity

### ISSUE THREAD

**Issue by fukien** [snowkylin/line#9]
According to the original paper, the second-order similarity should be the concatenation of the embeddings and context embeddings. Maybe you miss the concatenation operation.

**Comment by snowkylin** [comment]
Hi, could you please point out the specific paragraph in the original paper that describes the concatenation operation of second-order similarity? Note that the original paper describes LINE (1st+2nd) which concatenates the 1st LINE and 2nd LINE, which do not mean a concatenation of the embeddings and context embeddings.

**Comment by fukien** [comment]
Sorry, I misunderstood the paper.
